### ISSUE TITLE
Rename Dockerfile-app to Dockerfile

### ISSUE THREAD

**Issue by jameslamb** [uptake/groundhog#5]
This project has only one `Dockerfile`, used to run `groundhog` service. Since it's the only one in the repo, it's name should be changed to `Dockerfile` from `Dockerfile-app`.

Might also be a good idea to put all the service stuff in a folder like `app/` and move client(s) into a top-level folder called `clients/`

**Comment by dsudduth** [comment]
Hi @jameslamb,

I've created a PR to address the items in this issue. Please let me know if additional changes are needed.
